[versions]
spotless = "7.0.0.BETA4"
precompose = "1.6.2"
maleficnav = "1.1.3"
maleficextensions = "1.1.4"
maleficcomps = "1.0.5"
malefictheme = "1.0.2"

[libraries]
precompose = { module = "moe.tlaster:precompose", version.ref = "precompose" }
malefic-nav = { module = "xyz.malefic:maleficnav", version.ref = "maleficnav" }
malefic-extensions = { module = "xyz.malefic:maleficextensions", version.ref = "maleficextensions" }
malefic-components = { module = "xyz.malefic:maleficcomponents", version.ref = "maleficcomps" }
malefic-theming = { module = "xyz.malefic:malefictheming", version.ref = "malefictheme" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
